version: '3.9'
services:
  website:
    build: 
      dockerfile: dockerfile-website
      tags:
        - "docker.hostag.fr/bingehub-website:${npm_package_version}"
    ports:
      - "3000:3000"
    image: "docker.hostag.fr/bingehub-website:${npm_package_version}"
  cms:
    build: 
      dockerfile: dockerfile-cms
      tags:
        - "docker.hostag.fr/bingehub-cms:${npm_package_version}"
    image: "docker.hostag.fr/bingehub-cms:${npm_package_version}"
