version: '3.9'
services:
  # website:
  #   build:
  #     dockerfile: dockerfile-website
  #     tags:
  #       - 'docker.hostag.fr/bingehub-website:${npm_package_version}'
  #   ports:
  #     - '3000:3000'
  #   image: 'docker.hostag.fr/bingehub-website:${npm_package_version}'
  #   env_file:
  #     - .env
  #   volumes:
  #     - Z:\torrent:/library
  #   user: '0:0'
  cms:
    build:
      dockerfile: dockerfile-cms
      tags:
        - 'docker.hostag.fr/bingehub-cms:${npm_package_version}'
    image: 'docker.hostag.fr/bingehub-cms:${npm_package_version}'
    env_file:
      - .env
    volumes:
      - /mnt/silverstone/torrent:/library
    user: '0:0'
