FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy package.json @ root and in workspaces
COPY package*.json ./
COPY cms/package*.json ./cms/
COPY website/package*.json ./website/

# Install dependencies
RUN npm ci --workspace=cms

# Copy source code
COPY . .

# Install ffmpeg
RUN apk add  --no-cache ffmpeg

# Build website
RUN npm run prisma:generate
RUN npm run build --workspace=cms
WORKDIR /app/cms
CMD ["npm", "run", "start"]
