FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy package.json @ root and in workspaces
COPY package*.json ./
COPY cms/package*.json ./cms/
COPY website/package*.json ./website/

# Install dependencies
RUN npm ci --workspace=website

# Copy source code
COPY . .

# Build website
RUN npm run build --workspace=website
WORKDIR /app/website
CMD ["npm", "run", "start"]
